# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic binary PLY fixtures used by unit/integration tests."""

from __future__ import annotations

import pathlib
import struct


ROOT = pathlib.Path(__file__).parents[1] / "tests" / "fixtures"
PROPERTIES = (
    "x",
    "y",
    "z",
    "scale_0",
    "scale_1",
    "scale_2",
    "rot_0",
    "rot_1",
    "rot_2",
    "rot_3",
    "opacity",
    "f_dc_0",
    "f_dc_1",
    "f_dc_2",
)


def header() -> bytes:
    lines = [
        "ply",
        "format binary_little_endian 1.0",
        "comment generated by tools/generate_fixtures.py",
        "element vertex 1",
        *(f"property float {name}" for name in PROPERTIES),
        "end_header",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    values = (
        1.0,
        2.0,
        3.0,
        0.0,
        0.69314718056,
        -0.69314718056,
        2.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.1,
        0.2,
        0.3,
    )
    payload = struct.pack("<14f", *values)
    (ROOT / "one-gaussian-binary-le.ply").write_bytes(header() + payload)
    (ROOT / "truncated-binary-le.ply").write_bytes(header() + payload[:12])


if __name__ == "__main__":
    main()
