# SPDX-License-Identifier: Apache-2.0
"""Generate deterministic binary PLY fixtures used by unit/integration tests."""

from __future__ import annotations

import math
import pathlib
import struct


ROOT = pathlib.Path(__file__).parents[1] / "tests" / "fixtures"
BASE_PROPERTIES = (
    "x",
    "y",
    "z",
    "scale_0",
    "scale_1",
    "scale_2",
    "rot_0",
    "rot_1",
    "rot_2",
    "rot_3",
    "opacity",
    "f_dc_0",
    "f_dc_1",
    "f_dc_2",
)


def header(vertex_count: int, properties: tuple[str, ...]) -> bytes:
    lines = [
        "ply",
        "format binary_little_endian 1.0",
        "comment generated by tools/generate_fixtures.py",
        f"element vertex {vertex_count}",
        *(f"property float {name}" for name in properties),
        "end_header",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def pack_rows(rows: list[tuple[float, ...]]) -> bytes:
    return b"".join(struct.pack(f"<{len(row)}f", *row) for row in rows)


def one_gaussian() -> None:
    values = (
        1.0,
        2.0,
        3.0,
        0.0,
        0.69314718056,
        -0.69314718056,
        2.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.1,
        0.2,
        0.3,
    )
    payload = pack_rows([values])
    head = header(1, BASE_PROPERTIES)
    (ROOT / "one-gaussian-binary-le.ply").write_bytes(head + payload)
    (ROOT / "truncated-binary-le.ply").write_bytes(head + payload[:12])


def three_gaussians() -> None:
    """Multi-Gaussian fixture: asymmetric scales, non-identity rotations,
    distinct opacities, and degree-1 SH (f_rest is channel-major R G B)."""
    properties = BASE_PROPERTIES + tuple(f"f_rest_{i}" for i in range(9))
    rows = [
        (1.0, 2.0, 3.0,
         0.0, 0.5, 1.0,
         1.0, 0.0, 0.0, 0.0,
         -1.0,
         0.1, 0.2, 0.3,
         1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0),
        (-4.0, 5.0, -6.0,
         -1.0, 0.0, 0.25,
         0.5, 0.5, 0.5, 0.5,
         0.0,
         0.4, 0.5, 0.6,
         11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0),
        (7.0, -8.0, 9.0,
         2.0, -0.5, 0.0,
         2.0, 0.0, 0.0, 2.0,
         2.0,
         -0.7, 0.8, -0.9,
         21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0),
    ]
    (ROOT / "three-gaussian-binary-le.ply").write_bytes(
        header(3, properties) + pack_rows(rows))


def nan_opacity() -> None:
    values = (
        1.0, 2.0, 3.0,
        0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0,
        math.nan,
        0.1, 0.2, 0.3,
    )
    (ROOT / "nan-opacity-binary-le.ply").write_bytes(
        header(1, BASE_PROPERTIES) + pack_rows([values]))


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    one_gaussian()
    three_gaussians()
    nan_opacity()


if __name__ == "__main__":
    main()
